projects:
  unlok:
    schema: http://localhost:8000/graphql
    documents: graphql/lok/*/**.graphql
    extensions:
      turms:
        out_dir: lok/api
        freeze: True
        stylers:
          - type: turms.stylers.default.DefaultStyler
          - type: turms.stylers.appender.AppenderStyler
            append_fragment: "Fragment"
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_kwargs:
              - type: lok.rath.LokRath
                key: rath
                description: "The client we want to use (defaults to the currently active client)"
            definitions:
              - type: subscription
                is_async: True
                use: lok.funcs.asubscribe
              - type: query
                is_async: True
                use: lok.funcs.aexecute
              - type: mutation
                is_async: True
                use: lok.funcs.aexecute
              - type: subscription
                use: lok.funcs.subscribe
              - type: query
                use: lok.funcs.execute
              - type: mutation
                use: lok.funcs.execute
        processors:
          - type: turms.processors.black.BlackProcessor
        scalar_definitions:
          uuid: str
          Any: typing.Any
          ID: rath.scalars.ID
